using System.Collections.Generic;
using UnityEngine;

// -----------------------------------------------------------------------------
// V2.2 ItemDatabase
// -----------------------------------------------------------------------------
// Singleton ScriptableObject that holds every generated ItemDefinition for fast
// lookup at runtime. Lives at Assets/Resources/ItemDatabase.asset and is loaded
// via Resources.Load. Populated by Assets/Editor/Data/ItemSoGenerator.cs from
// items.json + categories.json.
//
// Field name notes:
//   - The serialized list field is still called `items` (not `allItems`) so the
//     existing .asset's YAML and the many call sites that write `db.items.Add(...)`
//     (AutomationSetupNN, RegisterVehiclePartsEditor, BuildingItemSetup, …) keep
//     working without churn. `AllItems` exposes the same data as a read-only view.
//
// Coop note: read-only data registry. No runtime mutation outside editor tools.
// -----------------------------------------------------------------------------

[CreateAssetMenu(fileName = "ItemDatabase", menuName = "Voidborne/Items/Item Database (v2)")]
public class ItemDatabase : ScriptableObject
{
    /// <summary>Cached singleton, populated in <see cref="OnEnable"/>. Use <see cref="GetOrLoad"/> for safe access.</summary>
    public static ItemDatabase Instance { get; private set; }

    [Tooltip("All ItemDefinitions generated by Volume 2.2 (id-sorted).")]
    public List<ItemDefinition> items = new List<ItemDefinition>();

    // Lookup cache, built lazily. _lookupBuiltForCount tracks the items.Count
    // snapshot used; if items grows after BuildLookup ran (the generator path),
    // a subsequent GetItem call rebuilds.
    private Dictionary<string, ItemDefinition> _byId;
    private int _lookupBuiltForCount = -1;

    private void OnEnable()
    {
        Instance = this;
        BuildLookup();
    }

    /// <summary>Force-rebuilds the id lookup. Called by the generator after assigning items.</summary>
    public void Reindex() => BuildLookup();

    private void BuildLookup()
    {
        int count = items?.Count ?? 0;
        _byId = new Dictionary<string, ItemDefinition>(count);
        _lookupBuiltForCount = count;
        if (items == null) return;
        foreach (var def in items)
        {
            if (def == null) continue;
            if (string.IsNullOrEmpty(def.itemId)) continue;
            if (_byId.ContainsKey(def.itemId))
            {
                Debug.LogWarning($"[ItemDatabase] Duplicate item ID '{def.itemId}' — skipping second entry.", this);
                continue;
            }
            _byId[def.itemId] = def;
        }
    }

    /// <summary>Read-only view of every registered item.</summary>
    public IReadOnlyList<ItemDefinition> AllItems => items;

    /// <summary>O(1) lookup by item ID. Returns null when not found.</summary>
    public ItemDefinition GetItem(string id)
    {
        if (string.IsNullOrEmpty(id)) return null;
        // Rebuild if stale — OnEnable may have fired before the items list was
        // populated (the generator path) or before deserialized references resolved.
        int currentCount = items?.Count ?? 0;
        if (_byId == null || _lookupBuiltForCount != currentCount)
            BuildLookup();
        _byId.TryGetValue(id, out var def);
        return def;
    }

    /// <summary>Enumerates every item whose <see cref="ItemDefinition.categories"/> list contains <paramref name="category"/>.</summary>
    public IEnumerable<ItemDefinition> ByCategory(string category)
    {
        if (string.IsNullOrEmpty(category) || items == null) yield break;
        foreach (var def in items)
        {
            if (def == null) continue;
            if (def.HasCategory(category)) yield return def;
        }
    }

    /// <summary>Enumerates every item whose <see cref="ItemDefinition.kind"/> equals <paramref name="kind"/>.</summary>
    public IEnumerable<ItemDefinition> ByKind(ItemKind kind)
    {
        if (items == null) yield break;
        foreach (var def in items)
        {
            if (def == null) continue;
            if (def.kind == kind) yield return def;
        }
    }

    /// <summary>
    /// Resolves the active ItemDatabase, loading from <c>Assets/Resources/ItemDatabase.asset</c>
    /// if the static <see cref="Instance"/> hasn't been initialised yet.
    /// </summary>
    public static ItemDatabase GetOrLoad()
    {
        if (Instance != null) return Instance;
        var loaded = Resources.Load<ItemDatabase>("ItemDatabase");
        if (loaded == null)
        {
            Debug.LogError("[ItemDatabase] No ItemDatabase found in Resources. Run Voidborne/Generate/Items to create one.");
            return null;
        }
        Instance = loaded;
        return loaded;
    }
}
